name: Tests

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Cache Yarn dependencies
      uses: actions/cache@v2
      with:
        path: ~/.cache/yarn
        key: yarn-${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          yarn-${{ runner.os }}-

    - name: Install dependencies
      run: yarn install

    - name: Run tests
      run: yarn test
